### ISSUE TITLE
Cannot get my referrer value after your app installed from Google Play

### ISSUE THREAD

**Issue by nghianguyen979** [SimonMarquis/Android-InstallReferrer#4]
fdf

Fous on this link to test referrer value as your suggestion:
https://play.google.com/store/apps/details?id=fr.simon.marquis.installreferrer&referrer=myReferrerValue
____
I opened link above on our browser device android -> navigate to store and install, but after app launch, I didn't get referrer = myReferrerValue, but it returns to me referrer = utm_source =google, utm_..... 

Can you help me explain this case?

**Comment by SimonMarquis** [comment]
If you open a browser and paste this url, it will load the web version of the Google Play Store instead of the native one.
Unfortunately, the web version will either
- not forward the referrer value if you use the web "install" button
- override the referrer value if you use the web "open in app" button because it uses it's own play.app.goo.gl deeplink to open the native Play Store.

You should navigate to the url with a link (or through javascript) and not by pasting the url in the search bar, or use the other forms of links (market:// or intent:) .
